version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: ai-consultant-db-local
    environment:
      POSTGRES_DB: telegram_bot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./migrations:/migrations
    restart: unless-stopped